"""add clean_sheets

Revision ID: 0f13b6f1e724
Revises: bc3797118b23
Create Date: 2026-02-14 16:29:06.642463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f13b6f1e724'
down_revision = 'bc3797118b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('club')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('stadium', sa.VARCHAR(length=100), nullable=True),
    sa.Column('founded', sa.INTEGER(), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.VARCHAR(length=50), nullable=True),
    sa.Column('club_id', sa.INTEGER(), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('img', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
