"""add nationality to player

Revision ID: ecf404c378cb
Revises: 49ccba21517f
Create Date: 2026-02-03 10:15:17.761274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf404c378cb'
down_revision = '49ccba21517f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('stadium',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('founded',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('img')
        batch_op.drop_column('nationality')

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('founded',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stadium',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
